# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Text-Trade' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  #use_modular_headers!
  
  # Pods for Text-Trade
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'

end
